name: Deploy Ampache

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: latest

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: S3 music
      run: aws s3 cp ./music s3://ampache-bucket-956789/music/ --recursive
    
    
