name: test

on:
  push:
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Docker Compose up
        uses: hoverkraft-tech/compose-action@v0.0.0
        with:
          compose-file: ./docker-compose.yml
          up-flags: --build

      - name: Wait for Ampache
        env:
          AMPACHE_PORT: ${{ secrets.AMPACHE_PORT || '80' }}
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:$AMPACHE_PORT >/dev/null; then
              echo "Ampache is up!"
              exit 0
            fi
            sleep 2
          done
          echo "Ampache did not start in time" >&2
          exit 1

      - name: Docker Compose down
        if: always()
        uses: hoverkraft-tech/compose-action@v0.0.0
        with:
          compose-file: ./docker-compose.yml
          down-flags: --volumes
